server:
  port: 7000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    
 
spring:
  application:
    name: crusoeui