server:
  port: 7000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    
 
spring:
  application:
    name: crusoeui
  jpa:
    hibernate:
      ddl-auto: update
  database: MYSQL
  datasource:
    url: jdbc:mysql://10.132.23.119:3306/flowable-spring-boot?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true
    username: root
    password: tomtom1982