spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable-spring-boot?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: tomtom1982
flowable:
#关闭定时任务JOB
  async-executor-activate: false
