server:
  port: 8091
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
 
spring:
  application:
    name: eureka-consumer-feign
#开启Hystrix
feign:
  hystrix:
    enabled: true