server:
  port: 6601
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
 
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: baidu
        uri: http://www.baidu.com/
        predicates:
        - Path=/baidu/**
        filters:
        - JwtCheck
      - id: auth-service
        uri: lb://oauth2-service/oauth/
        predicates:
        - Path=/oauth/**
  security:
    oauth2:
      client:
        authorization-uri: lb://oauth2-service/oauth/authorize
        token-uri: lb://oauth2-service/oauth/token
        client-id: webapp
  feign:
    hystrix:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG




