server:
  port: 6601
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
 
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: baidu
        uri: http://www.baidu.com/
        predicates:
        - Path=/baidu/**
        filters:
        - JwtCheck
      - id: auth-service
        uri: lb://oauth2-service/oauth/
        predicates:
        - Path=/oauth/**
  security:
    oauth2:
      client:
        registration:
          crusoe:
            client-id: webapp
            client-secret: 123456
            authorizationGrantType: implicit
            redirectUri: localhost:6601/
            provider: as
        provider:
          as:          
            authorization-uri: http://localhost:8080/oauth/authorize
            token-uri: http://localhost:8080/oauth/token

        

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


