eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
spring:
  application:
    name: eureka-sideserver
server:
  port: 8801    
sidecar:
  port: 8205
  health-uri: http://localhost:${sidecar.port}/health.json
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS