server:
  port: 9001
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
 
spring:
  application:
    name: oauth2-resourceserver
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        jwk-set-uri: lb://oauth2-service/token_key